jobs:
  run:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Fetch Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./verify/verify

name: Main

on:
  schedule:
    - cron: "50 */6 * * *"
